### PR TITLE
Add random greeter 

### PR DESCRIPTION
**Pull request by shasherazi**
In this PR, I created an app which
- has an index page with a link to random greeting page
- greets with a random message on every refresh

You can generate random messages like this in `rails console`
```
Greeting.create(message: "Hello!")
Greeting.create(message: "Hi there!")
Greeting.create(message: "Good morning!")
Greeting.create(message: "Hey, how's it going?")
Greeting.create(message: "Greetings!")
Greeting.create(message: "Salutations!")
Greeting.create(message: "Hey, what's up?")
Greeting.create(message: "Hola!")
Greeting.create(message: "Hey, howdy!")
Greeting.create(message: "Yo!")
```

and run the app with `./bin/dev`

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @shasherazi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive readme and doesn't follow gitflow pattern , kindly Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Davidosky007 — COMMENTED** [review]
Hi @shasherazi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive readme and doesn't follow gitflow pattern , kindly Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @shasherazi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that lacks a link to the frontend repo. Make sure you also add a link to the backend from the frontend readme file. Please make these changes and resend for a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by shasherazi** [comment]
Hi @afanimartin, this is the hello world project which is supposed to have only one app. I submitted the link to the wrong activity, sorry for that. I'm writing this for the next reviewer to clear up the confusion.

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢 🟢 🟢

Hi @shasherazi,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:
✅ You used Gitflow correctly 👍🏽
✅ The Linter checks passed 👍🏽
✅ Rails and React apps work fine as expected 👍🏽
✅ Generates random greetings and are rendered on the Front-end 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
